Add dock sensors
humbertogontijo/homeassistant-roborock pull request #233
Opened 2023-04-10 21:48 UTC by Lash-L

Wanted to just add sensors and since there were so many changes, I just wanted a clean start so I can build this on top of it and leave the last branch unaffected if I add services down the line.

2023-04-11 19:39 UTC, humbertogontijo commented
Is this open for review?

2023-04-11 19:54 UTC, humbertogontijo commented
I do not have it either. I will review it as it is and we can make the necessary changes

2023-04-11 19:55 UTC, humbertogontijo requested changes

2023-04-11 19:55 UTC, humbertogontijo commented on custom_components/roborock/sensor.py
> +        translation_key="dock_status",
And add for the new ones

2023-04-11 19:55 UTC, humbertogontijo commented on custom_components/roborock/sensor.py
> +        translation_key="last_clean_end",
Can you keep name property for all decriptions?

2023-04-11 20:01 UTC, Lash-L commented
fixed

2023-04-11 20:18 UTC, humbertogontijo approved these changes

2023-04-11 20:18 UTC, merged

2023-04-13 06:04 UTC, Menelao147 commented
Hi, I'm trying to translate the descriptions of the new sensor. Can you explain what they mean?

2023-04-13 13:16 UTC, Lash-L commented
@Menelao147 

dock_status is the status for docks. Ends up saying "okay" or "water low" or other things like that

wash_towel_mode - is the mode it will use to clean the mopping pad on the robot

dust collection mode - is how it will get the dust out of the robot. Basically how strong it will try to suction it out/ how long it will suction for.

dock_mop_wash_mode_interval - is the frequency at which the robot will return to the dock to get the mopping pad cleaned